-- ============================================================
-- PEHNAV — Seed Data
-- Run AFTER schema.sql
-- Migrates all static data from data.ts into Supabase
-- ============================================================

-- Categories
insert into public.categories (id, name_en, name_hi, image_url, product_group, sort_order) values
('tees',        'Oversized Tees',   'ओवरसाइज़्ड टीज़',    '/assets/product-tee.jpg',         'apparel',      1),
('shirts',      'Shirts',           'शर्ट्स',               '/assets/product-shirt.jpg',        'apparel',      2),
('hoodies',     'Hoodies',          'हुडीज़',               '/assets/product-hoodie.jpg',       'apparel',      3),
('sweatshirts', 'Sweatshirts',      'स्वेटशर्ट्स',          '/assets/product-sweatshirt.jpg',   'apparel',      4),
('knitwear',    'Knitwear',         'निटवियर',              '/assets/product-knit.jpg',         'apparel',      5),
('jackets',     'Jackets',          'जैकेट्स',              '/assets/product-jacket.jpg',       'apparel',      6),
('cargo',       'Cargo Pants',      'कार्गो पैंट्स',         '/assets/product-cargo.jpg',        'apparel',      7),
('joggers',     'Joggers',          'जॉगर्स',               '/assets/product-joggers.jpg',      'apparel',      8),
('denim',       'Denim',            'डेनिम',                '/assets/product-denim.jpg',        'apparel',      9),
('sneakers',    'Sneakers',         'स्नीकर्स',              '/assets/product-sneakers.jpg',     'footwear',     10),
('caps',        'Caps & Hats',      'कैप्स और हैट्स',        '/assets/product-cap.jpg',          'accessories',  11),
('bags',        'Bags',             'बैग्स',                '/assets/product-bag.jpg',          'accessories',  12),
('eyewear',     'Eyewear',          'आईवियर',               '/assets/product-sunglasses.jpg',   'accessories',  13),
('belts',       'Belts',            'बेल्ट्स',              '/assets/product-belt.jpg',         'accessories',  14),
('watches',     'Watches',          'घड़ियाँ',               '/assets/product-watch.jpg',        'accessories',  15);

-- Collections
insert into public.collections (id, name_en, name_hi, tagline_en, tagline_hi, description_en, description_hi, image_url, sort_order) values
('dreamers',   'Dreamers',   'ड्रीमर्स',   'For those who imagine more',   'उनके लिए जो ज़्यादा सोचते हैं',   'Soft silhouettes and quiet confidence for the ones who chase the unseen.',                         'उनके लिए कोमल सिल्हूट और शांत आत्मविश्वास जो अनदेखे का पीछा करते हैं।',  '/assets/product-tee.jpg',     1),
('hustlers',   'Hustlers',   'हसलर्स',     'Built to keep moving',         'चलते रहने के लिए बना',             'Hard-wearing utility pieces for the relentless and the restless.',                                'अथक और बेचैन लोगों के लिए मज़बूत यूटिलिटी कपड़े।',                        '/assets/product-cargo.jpg',   2),
('creators',   'Creators',   'क्रिएटर्स',   'Make it yours',                'इसे अपना बनाओ',                   'Statement layers and bold textures for the makers and the breakers.',                            'रचनाकारों के लिए बोल्ड बनावट और स्टेटमेंट लेयर्स।',                       '/assets/product-hoodie.jpg',  3),
('wanderers',  'Wanderers',  'वांडरर्स',   'Everywhere is home',           'हर जगह घर है',                    'Easy, travel-ready essentials for the ones who never settle.',                                    'उनके लिए आरामदायक, यात्रा के लिए तैयार ज़रूरतें जो कभी नहीं रुकते।',     '/assets/product-shirt.jpg',   4);

-- Products (52 total)
insert into public.products (id, name_en, name_hi, price, compare_at, image_url, gallery, category, product_group, gender, collection, colors, sizes, badge, story_en, description_en, story_hi, description_hi) values
('ember-oversized-tee','Ember Oversized Tee','एम्बर ओवरसाइज़्ड टी',999,1499,'/assets/product-tee.jpg','{}','tees','apparel','unisex','dreamers','{"#000000","#D8C3A5"}','{"S","M","L","XL","XXL"}','bestseller','Cut for stillness and motion alike — Ember moves the way a dream does.','240 GSM heavyweight combed cotton with a relaxed drop-shoulder fit and tonal embroidery.','Cut for stillness and motion alike — Ember moves the way a dream does.','240 GSM heavyweight combed cotton with a relaxed drop-shoulder fit and tonal embroidery.'),
('halo-boxy-tee','Halo Boxy Tee','हेलो बॉक्सी टी',899,null,'/assets/v-tee-crop.jpg','{}','tees','apparel','women','dreamers','{"#000000","#D8C3A5"}','{"XS","S","M","L"}','new','The everyday hero with a softer halo.','Lightweight 180 GSM cotton with a cropped boxy fit.','The everyday hero with a softer halo.','Lightweight 180 GSM cotton with a cropped boxy fit.'),
('echo-graphic-tee','Echo Graphic Tee','इको ग्राफिक टी',1099,1399,'/assets/v-tee-graphic.jpg','{}','tees','apparel','unisex','creators','{"#000000","#F5F5F5"}','{"S","M","L","XL","XXL"}',null,'A quiet statement that speaks for itself.','230 GSM cotton with a hand-drawn back print and ribbed collar.','A quiet statement that speaks for itself.','230 GSM cotton with a hand-drawn back print and ribbed collar.'),
('aura-crop-tee','Aura Crop Tee','ऑरा क्रॉप टी',849,1199,'/assets/v-tee-crop.jpg','{}','tees','apparel','women','dreamers','{"#000000","#D8C3A5","#BFA16A"}','{"XS","S","M","L"}','bestseller','Light as a thought, bold as a move.','Soft modal-cotton blend with a cropped relaxed cut.','Light as a thought, bold as a move.','Soft modal-cotton blend with a cropped relaxed cut.'),
('midnight-hoodie','Midnight Heavy Hoodie','मिडनाइट हेवी हुडी',1799,2499,'/assets/product-hoodie.jpg','{}','hoodies','apparel','men','creators','{"#000000","#D8C3A5"}','{"S","M","L","XL","XXL"}','new','Built for late-night ideas and early-morning wins.','Brushed fleece interior, double-lined hood and a clean minimal silhouette.','Built for late-night ideas and early-morning wins.','Brushed fleece interior, double-lined hood and a clean minimal silhouette.'),
('forge-zip-hoodie','Forge Zip Hoodie','फोर्ज ज़िप हुडी',1999,2799,'/assets/v-hoodie-zip.jpg','{}','hoodies','apparel','unisex','hustlers','{"#000000","#F5F5F5"}','{"S","M","L","XL","XXL"}','bestseller','Forged for those who build their own path.','Premium full-zip with YKK hardware and an oversized hood.','Forged for those who build their own path.','Premium full-zip with YKK hardware and an oversized hood.'),
('nova-cropped-hoodie','Nova Cropped Hoodie','नोवा क्रॉप्ड हुडी',1599,1999,'/assets/v-hoodie-crop.jpg','{}','hoodies','apparel','women','creators','{"#000000","#D8C3A5","#BFA16A"}','{"XS","S","M","L"}','new','Bold lines, soft heart.','Cropped fleece hoodie with a ribbed hem and kangaroo pocket.','Bold lines, soft heart.','Cropped fleece hoodie with a ribbed hem and kangaroo pocket.'),
('atlas-crew-sweatshirt','Atlas Crew Sweatshirt','एटलस क्रू स्वेटशर्ट',1499,null,'/assets/product-sweatshirt.jpg','{}','sweatshirts','apparel','unisex','creators','{"#000000","#D8C3A5"}','{"S","M","L","XL","XXL"}','bestseller','Carry your world, comfortably.','Heavyweight french-terry crewneck with dropped shoulders.','Carry your world, comfortably.','Heavyweight french-terry crewneck with dropped shoulders.'),
('pulse-half-zip-sweat','Pulse Half-Zip Sweat','पल्स हाफ-ज़िप स्वेट',1699,2199,'/assets/v-sweat-halfzip.jpg','{}','sweatshirts','apparel','men','hustlers','{"#000000","#F5F5F5"}','{"S","M","L","XL","XXL"}','new','Keep the momentum.','Mid-weight half-zip with a funnel neck and ribbed cuffs.','Keep the momentum.','Mid-weight half-zip with a funnel neck and ribbed cuffs.'),
('harbor-knit-cardigan','Harbor Knit Cardigan','हार्बर निट कार्डिगन',2199,2799,'/assets/product-knit.jpg','{}','knitwear','apparel','unisex','wanderers','{"#D8C3A5","#BFA16A"}','{"S","M","L","XL","XXL"}','limited','Wrap yourself in calm.','Ribbed cotton-wool blend cardigan with corozo buttons.','Wrap yourself in calm.','Ribbed cotton-wool blend cardigan with corozo buttons.'),
('frost-crew-knit','Frost Crew Knit','फ्रॉस्ट क्रू निट',1899,null,'/assets/v-knit-crew.jpg','{}','knitwear','apparel','men','creators','{"#000000","#D8C3A5"}','{"S","M","L","XL","XXL"}',null,'Texture you can feel.','Chunky ribbed crewneck knit in a relaxed silhouette.','Texture you can feel.','Chunky ribbed crewneck knit in a relaxed silhouette.'),
('willow-knit-vest','Willow Knit Vest','विलो निट वेस्ट',1599,1999,'/assets/v-knit-vest.jpg','{}','knitwear','apparel','women','dreamers','{"#D8C3A5","#BFA16A","#F5F5F5"}','{"XS","S","M","L"}','new','Layer light, look sharp.','Fine-gauge sleeveless knit vest with a V-neckline.','Layer light, look sharp.','Fine-gauge sleeveless knit vest with a V-neckline.'),
('voyager-bomber','Voyager Bomber Jacket','वोयाजर बॉम्बर जैकेट',3299,3999,'/assets/product-jacket.jpg','{}','jackets','apparel','men','hustlers','{"#000000","#D8C3A5"}','{"S","M","L","XL","XXL"}','bestseller','For takeoffs and turnarounds.','Water-repellent nylon bomber with ribbed trims and zip pockets.','For takeoffs and turnarounds.','Water-repellent nylon bomber with ribbed trims and zip pockets.'),
('aria-puffer-jacket','Aria Cropped Puffer','एरिया क्रॉप्ड पफर',3499,4299,'/assets/v-jacket-puffer.jpg','{}','jackets','apparel','women','creators','{"#000000","#D8C3A5","#BFA16A"}','{"XS","S","M","L"}','limited','Lightweight warmth, heavyweight presence.','Recycled-fill cropped puffer with a stand collar.','Lightweight warmth, heavyweight presence.','Recycled-fill cropped puffer with a stand collar.'),
('ranger-denim-jacket','Ranger Denim Jacket','रेंजर डेनिम जैकेट',2599,null,'/assets/v-jacket-denim.jpg','{}','jackets','apparel','men','creators','{"#000000","#D8C3A5"}','{"S","M","L","XL","XXL"}',null,'An icon, reimagined.','Rigid denim trucker jacket with tonal stitching.','An icon, reimagined.','Rigid denim trucker jacket with tonal stitching.'),
('drift-cargo','Drift Cargo Pants','ड्रिफ्ट कार्गो पैंट्स',1599,null,'/assets/product-cargo.jpg','{}','cargo','apparel','men','hustlers','{"#000000","#D8C3A5"}','{"28","30","32","34","36"}','bestseller','Six pockets, zero compromise — for the ones always on the move.','Durable ripstop cotton with tapered ankles and utility cargo pockets.','Six pockets, zero compromise — for the ones always on the move.','Durable ripstop cotton with tapered ankles and utility cargo pockets.'),
('nomad-wide-cargo','Nomad Wide Cargo','नोमैड वाइड कार्गो',1699,null,'/assets/product-cargo.jpg','{}','cargo','apparel','unisex','wanderers','{"#000000","#D8C3A5","#BFA16A"}','{"28","30","32","34","36"}','new','Wide-leg freedom for the open road.','Relaxed wide-leg cargo with adjustable hem drawcords.','Wide-leg freedom for the open road.','Relaxed wide-leg cargo with adjustable hem drawcords.'),
('luna-parachute-cargo','Luna Parachute Cargo','लूना पैराशूट कार्गो',1799,2199,'/assets/v-cargo-parachute.jpg','{}','cargo','apparel','women','creators','{"#000000","#F5F5F5","#D8C3A5"}','{"XS","S","M","L"}','new','Float through the day.','Lightweight parachute cargo with elastic ankle toggles.','Float through the day.','Lightweight parachute cargo with elastic ankle toggles.'),
('pace-tech-joggers','Pace Tech Joggers','पेस टेक जॉगर्स',1499,null,'/assets/v-jogger-tech.jpg','{}','joggers','apparel','men','hustlers','{"#000000","#D8C3A5"}','{"28","30","32","34","36"}','bestseller','Move first, think later.','Four-way stretch tech-knit joggers with zip pockets.','Move first, think later.','Four-way stretch tech-knit joggers with zip pockets.'),
('raw-selvedge-jeans','Raw Selvedge Jeans','रॉ सेल्वेज जीन्स',2499,null,'/assets/product-denim.jpg','{}','denim','apparel','men','creators','{"#000000","#D8C3A5"}','{"28","30","32","34","36"}','bestseller','They get better with every wear.','14oz raw selvedge denim with a straight tapered leg.','They get better with every wear.','14oz raw selvedge denim with a straight tapered leg.'),
('azure-wide-jeans','Azure Wide-Leg Jeans','एज़ूर वाइड-लेग जीन्स',2299,2899,'/assets/v-denim-wide.jpg','{}','denim','apparel','women','dreamers','{"#000000","#D8C3A5","#F5F5F5"}','{"28","30","32","34","36"}','new','Room to breathe, room to move.','Rigid wide-leg denim with a high-rise waist.','Room to breathe, room to move.','Rigid wide-leg denim with a high-rise waist.'),
('dusk-baggy-jeans','Dusk Baggy Jeans','डस्क बैगी जीन्स',2399,2999,'/assets/v-denim-baggy.jpg','{}','denim','apparel','unisex','creators','{"#000000","#D8C3A5","#BFA16A"}','{"28","30","32","34","36"}','limited','Oversized, on purpose.','Heavyweight baggy denim with a relaxed drop crotch.','Oversized, on purpose.','Heavyweight baggy denim with a relaxed drop crotch.'),
('cloud-low-sneakers','Cloud Low Sneakers','क्लाउड लो स्नीकर्स',2999,3799,'/assets/product-sneakers.jpg','{}','sneakers','footwear','unisex','wanderers','{"#000000","#F5F5F5"}','{"UK6","UK7","UK8","UK9","UK10","UK11"}','bestseller','Walk on clouds, leave a mark.','Premium leather low-tops with a cushioned EVA midsole.','Walk on clouds, leave a mark.','Premium leather low-tops with a cushioned EVA midsole.'),
('pivot-court-sneakers','Pivot Court Sneakers','पिवट कोर्ट स्नीकर्स',2799,null,'/assets/v-sneaker-court.jpg','{}','sneakers','footwear','men','hustlers','{"#000000","#F5F5F5"}','{"UK6","UK7","UK8","UK9","UK10","UK11"}','new','Built for the everyday game.','Minimal court sneakers with a grippy rubber outsole.','Built for the everyday game.','Minimal court sneakers with a grippy rubber outsole.'),
('mist-runner-sneakers','Mist Runner Sneakers','मिस्ट रनर स्नीकर्स',3199,3899,'/assets/v-sneaker-runner.jpg','{}','sneakers','footwear','women','dreamers','{"#D8C3A5","#F5F5F5"}','{"UK6","UK7","UK8","UK9","UK10","UK11"}',null,'Light steps, long days.','Knit-upper runners with a breathable mesh lining.','Light steps, long days.','Knit-upper runners with a breathable mesh lining.'),
('heritage-cap','Heritage Two-Tone Cap','हेरिटेज टू-टोन कैप',699,null,'/assets/product-cap.jpg','{}','caps','accessories','unisex','wanderers','{"#000000","#D8C3A5"}','{"One Size"}','bestseller','Top off your story.','Cotton-twill six-panel cap with an adjustable strap.','Top off your story.','Cotton-twill six-panel cap with an adjustable strap.'),
('dune-bucket-hat','Dune Bucket Hat','ड्यून बकेट हैट',799,999,'/assets/v-bucket-hat.jpg','{}','caps','accessories','unisex','creators','{"#000000","#D8C3A5","#BFA16A"}','{"One Size"}','new','Shade, your way.','Reversible cotton bucket hat with a structured brim.','Shade, your way.','Reversible cotton bucket hat with a structured brim.'),
('carryall-tote','Carryall Canvas Tote','कैरीऑल कैनवस टोट',1499,null,'/assets/product-bag.jpg','{}','bags','accessories','unisex','wanderers','{"#000000","#D8C3A5"}','{"One Size"}','bestseller','Everything you need, nothing you don''t.','Heavy canvas tote with leather trims and a detachable strap.','Everything you need, nothing you don''t.','Heavy canvas tote with leather trims and a detachable strap.'),
('transit-crossbody','Transit Crossbody Bag','ट्रांज़िट क्रॉसबॉडी बैग',1299,1699,'/assets/v-bag-crossbody.jpg','{}','bags','accessories','unisex','hustlers','{"#000000","#D8C3A5"}','{"One Size"}','new','Hands free, mind clear.','Water-resistant crossbody with multiple zip compartments.','Hands free, mind clear.','Water-resistant crossbody with multiple zip compartments.'),
('atlas-backpack','Atlas Daypack','एटलस डेपैक',2199,2799,'/assets/v-bag-backpack.jpg','{}','bags','accessories','unisex','wanderers','{"#000000","#D8C3A5"}','{"One Size"}','limited','Carry your world.','Padded laptop daypack with a 22L capacity and roll-top.','Carry your world.','Padded laptop daypack with a 22L capacity and roll-top.'),
('eclipse-sunglasses','Eclipse Round Sunglasses','इक्लिप्स राउंड सनग्लासेस',1199,null,'/assets/product-sunglasses.jpg','{}','eyewear','accessories','unisex','creators','{"#000000","#BFA16A"}','{"One Size"}','bestseller','See the world, your way.','Matte acetate round frames with UV400 polarized lenses.','See the world, your way.','Matte acetate round frames with UV400 polarized lenses.'),
('vista-square-sunglasses','Vista Square Sunglasses','विस्टा स्क्वायर सनग्लासेस',1299,1699,'/assets/v-eyewear-square.jpg','{}','eyewear','accessories','unisex','wanderers','{"#000000","#BFA16A"}','{"One Size"}','new','A sharper point of view.','Lightweight square frames with gradient polarized lenses.','A sharper point of view.','Lightweight square frames with gradient polarized lenses.'),
('forge-leather-belt','Forge Leather Belt','फोर्ज लेदर बेल्ट',999,null,'/assets/product-belt.jpg','{}','belts','accessories','men','hustlers','{"#000000","#D8C3A5"}','{"30","32","34","36","38"}',null,'Hold it all together.','Full-grain leather belt with a brushed-gold plate buckle.','Hold it all together.','Full-grain leather belt with a brushed-gold plate buckle.'),
('mono-reversible-belt','Mono Reversible Belt','मोनो रिवर्सिबल बेल्ट',1099,1399,'/assets/v-belt-reversible.jpg','{}','belts','accessories','unisex','creators','{"#000000","#D8C3A5"}','{"30","32","34","36","38"}','new','Two looks, one belt.','Reversible black-and-tan leather belt with a rotating buckle.','Two looks, one belt.','Reversible black-and-tan leather belt with a rotating buckle.'),
('meridian-watch','Meridian Leather Watch','मेरिडियन लेदर वॉच',3499,4299,'/assets/product-watch.jpg','{}','watches','accessories','unisex','creators','{"#000000","#BFA16A"}','{"One Size"}','limited','Time, beautifully kept.','Gold-tone case with a tan leather strap and sapphire crystal.','Time, beautifully kept.','Gold-tone case with a tan leather strap and sapphire crystal.'),
('pulse-minimal-watch','Pulse Minimal Watch','पल्स मिनिमल वॉच',2999,null,'/assets/v-watch-minimal.jpg','{}','watches','accessories','unisex','dreamers','{"#000000","#D8C3A5"}','{"One Size"}','new','Every second, considered.','Slim minimalist watch with a clean dial and quartz movement.','Every second, considered.','Slim minimalist watch with a clean dial and quartz movement.');

-- Blog Posts
insert into public.blog_posts (id, title_en, title_hi, category, excerpt_en, excerpt_hi, body_en, body_hi, image_url, published, published_at) values
('build-a-capsule-wardrobe','Build a Capsule Wardrobe','कैप्सूल वॉर्डरोब बनाएं','Style Guides','Ten pieces. Endless stories. Here''s how to start.','दस टुकड़े। अनंत कहानियाँ। यहाँ से शुरू करें।','Ten pieces. Endless stories. Start with the basics.','दस टुकड़े। अनंत कहानियाँ। बेसिक्स से शुरू करें।','/assets/product-tee.jpg',true,'2026-05-20'),
('the-art-of-layering','The Art of Layering','लेयरिंग की कला','Fashion','Master texture, proportion and contrast like an editor.','एक संपादक की तरह बनावट और कंट्रास्ट में महारत हासिल करें।','Master texture, proportion and contrast.','बनावट और कंट्रास्ट में महारत हासिल करें।','/assets/product-hoodie.jpg',true,'2026-05-12'),
('meet-the-creators','Meet the Creators','क्रिएटर्स से मिलें','Stories','The voices shaping PEHNAV''s next collection.','PEHNAV के अगले कलेक्शन को आकार देने वाली आवाज़ें।','Meet the creators behind the collection.','कलेक्शन के पीछे के क्रिएटर्स से मिलें।','/assets/campaign.jpg',true,'2026-04-30');
